[package]
name = "bellperson-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellperson = "0.18"
blstrs = "0.4"
rand = "0.8"
